-- AlterTable RSVP: cost commitment and reconfirm fields
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "costCommitmentAccepted" BOOLEAN;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "rsvpYesAcceptedAt" TIMESTAMP(3);
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "yesSubstatus" TEXT;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "acceptedEstimateLowCents" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "acceptedEstimateHighCents" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "acceptedHeadcountMin" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "acceptedHeadcountMax" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "acceptedCostBasisVersion" TEXT;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "reconfirmRequiredAt" TIMESTAMP(3);
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "reconfirmDeadlineAt" TIMESTAMP(3);
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "latestEstimateLowCents" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "latestEstimateHighCents" INTEGER;
ALTER TABLE "RSVP" ADD COLUMN IF NOT EXISTS "latestEstimateUpdatedAt" TIMESTAMP(3);
