/** Logged with each `emailLog` row — not external template IDs (emails are rendered in-app). */
export const TEMPLATE_KEYS = {
	// --- Existing ---
	GUEST_CONFIRMATION: 'GUEST_CONFIRMATION',
	TRIP_INVITE: 'TRIP_INVITE',
	WAITLIST_ADDED: 'WAITLIST_ADDED',
	SPOT_OPENED: 'SPOT_OPENED',

	// --- RSVP ---
	RSVP_CONFIRMED: 'RSVP_CONFIRMED',
	NEW_RSVP_HOST: 'NEW_RSVP_HOST',
	RSVP_UPDATED: 'RSVP_UPDATED',
	TRIP_FILLING_UP_50: 'TRIP_FILLING_UP_50',
	TRIP_FILLING_UP_75: 'TRIP_FILLING_UP_75',
	TRIP_FILLING_UP_90: 'TRIP_FILLING_UP_90',

	// --- Invitations / Membership ---
	GUEST_JOINED: 'GUEST_JOINED',
	REMOVED_FROM_TRIP: 'REMOVED_FROM_TRIP',
	TRIP_CANCELED: 'TRIP_CANCELED',
	WELCOME_CO_HOST: 'WELCOME_CO_HOST',
	BED_REMOVED: 'BED_REMOVED',

	// --- Time-based (sent by cron) ---
	INVITATION_REMINDER: 'INVITATION_REMINDER',
	TRIP_STARTING_SOON: 'TRIP_STARTING_SOON',
	DAY_OF_TRIP: 'DAY_OF_TRIP',
	DAILY_DIGEST: 'DAILY_DIGEST',
	TRIP_RECAP: 'TRIP_RECAP',
	FEEDBACK_REQUEST: 'FEEDBACK_REQUEST',

	// --- Cost re-approval ---
	COST_SHARE_REAPPROVAL_GUEST: 'COST_SHARE_REAPPROVAL_GUEST',
	COST_SHARE_REAPPROVAL_GUEST_REMINDER: 'COST_SHARE_REAPPROVAL_GUEST_REMINDER',
	COST_SHARE_REAPPROVAL_HOST_OVERDUE: 'COST_SHARE_REAPPROVAL_HOST_OVERDUE',
	GUEST_APPROVED_NEW_COST_SHARE: 'GUEST_APPROVED_NEW_COST_SHARE'
} as const;

export type EmailTemplateKey = (typeof TEMPLATE_KEYS)[keyof typeof TEMPLATE_KEYS];
